---
- name: Add git stable apt_repository on Ubuntu
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Install system packages and utils on ubuntu
  apt:
    pkg:
      [
        "openssl",
        "groff",
        "telnet",
        "s3fs",       # Tool to mount aws S3 to local storage
        "htop",
        "wget",
        "python3-pip",
        "zip",
        "unzip",
      ]
    state: present
    update_cache: true
    cache_valid_time: 5400
  changed_when: false

- name: Install python packages
  apt:
    name:
      - awscli
      - iotop
    state: present
