---
# Create main group for SFTP users.
- name: SFTP-Server | Create main sftp user group
  group:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ sftp_groups }}"

- name: SFTP-Server | Add 'Match Group' sshd_config block
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: '# {mark} SFTP-Server {{ item.name }} group block'
    block: |
      Match Group {{ item.name }}
          ForceCommand internal-sftp {{ item.sftp_enable_logging | ternary('-l VERBOSE', '') }}{% if item.readonly is defined and item.readonly %}-R{% endif %}{{''}}{% if item.default_directory_path is defined and item.default_directory_enabled %}-d {{ item.default_directory_path }}{% endif %}{{''}}
          ChrootDirectory %h
          PermitTunnel no
          AllowTCPForwarding no
          X11Forwarding no
          PasswordAuthentication {{ item.sftp_allow_passwords | ternary('yes', 'no') }}
          PubkeyAuthentication {% if sftp_enable_key_based_auth %}yes{%- else -%}no{% endif %}{{''}}
          AllowAgentForwarding no
  notify: SFTP-Server | Restart sshd
  with_items: "{{ sftp_groups }}"
