---

# Create each SFTP user with home directory on the correct partition, and add to SFTP group.
- name: SFTP-Server | Create sftp users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group | default(sftp_groups.0.name) }}"
    groups: "{{ (item.groups|default([])) + [sftp_groups.0.name] }}"
    append: "{{ item.append | default(False) }}"
    home: "{{ item.home | default('/home' + '/' + item.name) }}"
    uid: "{{ item.uid | default(omit) }}"
    # `None` means default value -> default is to have a shell
    shell: "{{ None if (item.shell | default(True)) else '/sbin/nologin' }}"
    state: present
  with_items: "{{ sftp_users }}"

# A working chrooted SFTP setup requires root:sftgroup ownership of a user's home directory.
- name: SFTP-Server | Correct ownership and permission of home directories
  file:
    path: "{{ item.home | default('/home' + '/' + item.name) }}"
    owner: root
    group: "{{ sftp_chroot_group | default(sftp_groups.0.name) }}"
    mode: "0750"
  with_items: "{{ sftp_users }}"

# Install all relevant public keys.
- name: SFTP-Server | Install public keys
  authorized_key:
    user: "{{ item.name }}"
    path: "{{ item.home | default('/home' + '/' + item.name) }}/.ssh/authorized_keys"
    key: "{{ item.key }}"
    manage_dir: true
  with_items:
    - "{{ sftp_users }}"
  when: item.key is defined

# Update user passwords, if they were specified.
- name: SFTP-Server | Update user passwords
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  with_items: "{{ sftp_users }}"
  when: item.update_password | default(False)

# Create directories for individual SFTP users. Optional.
- name: SFTP-Server | Create required directories per user
  file:
    path: "{{ item.extra_dir }}"
    owner: "{{ item.name }}"
    group: "{{ item.group | default(sftp_groups.0.name) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: directory
  with_items:
    - "{{ sftp_users }}"
  when: item.extra_dir is defined
